### ISSUE TITLE
nvdlib.searchCVE keywordSearch   times out

### ISSUE THREAD

**Issue by maxlinkh** [vehemont/nvdlib#27]
Hello developer, 
I'm using nvdlib-0.7.4 and when I execute the command below:
r = nvdlib.searchCVE(pubStartDate = start, pubEndDate = end,keywordSearch= 'xxxxx', cvssV3Severity = 'Critical', key='xxxxxxxxxxxxxxxxxxxx')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maxlin/.local/lib/python3.9/site-packages/nvdlib/cve.py", line 156, in searchCVE
    raw = __get('cve', headers, parameters, limit, verbose, delay)
  File "/home/maxlin/.local/lib/python3.9/site-packages/nvdlib/get.py", line 23, in __get
    raw = requests.get(link, params=stringParams, headers=headers, timeout=30)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='services.nvd.nist.gov', port=443): Read timed out. (read timeout=30)
If I remove "keywordSearch= 'xxxxx'" , it works fine. It is possible that the keyword has been banned.

Thank you

**Comment by maxlinkh** [comment]
The problem occurred after July.

thank you!

**Comment by vehemont** [comment]
Hi, 

This issue is being documented in #26. It is an issue with NVD servers, and not NVDLib.

**Comment by maxlinkh** [comment]
Thank you
